FIX php depecation error for video slides
Error: E_DEPRECATED: preg_match(): Passing null to parameter #2
($subject) of type string is deprecated

promo-overlay/src/models/PromoSlide.php:121

If no video is set, do not try to parse it for a YouTube video ID.